import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const fail = (message) => { console.error(`Release verification failed: ${message}`); process.exit(1); };
const htmlPath = path.join(root, "index.html");
const assetsDir = path.join(root, "assets");
if (!fs.existsSync(htmlPath)) fail("index.html is missing");
if (!fs.existsSync(assetsDir)) fail("assets/ is missing");
const assetFiles = fs.readdirSync(assetsDir).sort();
if (JSON.stringify(assetFiles) !== JSON.stringify(["app.css", "app.js"])) fail(`assets/ must contain only app.css and app.js; got ${assetFiles.join(", ")}`);
const html = fs.readFileSync(htmlPath, "utf8");
const refs = [...html.matchAll(/(?:src|href)=["']([^"']+)["']/g)].map((m) => m[1]).filter((x) => !x.startsWith("#"));
for (const forbidden of ["src/", "vendor/", "dist/"]) if (html.includes(forbidden)) fail(`index.html still references ${forbidden}`);
if (!refs.includes("assets/app.js") || !refs.includes("assets/app.css")) fail(`index.html must reference assets/app.js and assets/app.css; got ${refs.join(", ")}`);
const js = fs.readFileSync(path.join(assetsDir, "app.js"), "utf8");
for (const marker of ["Real Sky Observatory 5.5.7", "registerSkyData", "Celestial", "luxon", "tzlookup", "真实星空观测台 5.5.7 完整说明书"]) if (!js.includes(marker)) fail(`app.js missing marker: ${marker}`);
const css = fs.readFileSync(path.join(assetsDir, "app.css"), "utf8");
if (!css.includes("Real Sky Observatory 5.5.7")) fail("app.css missing build marker");
if (/url\([^)]*(?:\.png|\.gif|\.jpg|\.jpeg)/i.test(css)) fail("app.css still references an external local image");
console.log("Release verification passed: index.html + assets/app.js + assets/app.css are self-contained.");
